config/routes.rb
Rails.application.routes.draw do
  root "students#index"
  resources :students
  resources :assignments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  has_many :assignment_repos, class_name: 'AssignmentRepo'
  has_many :students, through: :assignment_repos
end

app/models/assignment_repo.rb
class AssignmentRepo < ApplicationRecord
  belongs_to :student
  belongs_to :assignment
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  validates :cohort, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assignment_repos_controller.rb
class AssignmentReposController < ApplicationController
  before_action :set_assignment_repo, only: %i[ show edit update destroy ]

  # GET /assignment_repos or /assignment_repos.json
  def index
    @assignment_repos = AssignmentRepo.all
  end

  # GET /assignment_repos/1 or /assignment_repos/1.json
  def show
  end

  # GET /assignment_repos/new
  def new
    @assignment_repo = AssignmentRepo.new
  end

  # GET /assignment_repos/1/edit
  def edit
  end

  # POST /assignment_repos or /assignment_repos.json
  def create
    @assignment_repo = AssignmentRepo.new(assignment_repo_params)

    respond_to do |format|
      if @assignment_repo.save
        format.html { redirect_to @assignment_repo, notice: "Assignment repo was successfully created." }
        format.json { render :show, status: :created, location: @assignment_repo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assignment_repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignment_repos/1 or /assignment_repos/1.json
  def update
    respond_to do |format|
      if @assignment_repo.update(assignment_repo_params)
        format.html { redirect_to @assignment_repo, notice: "Assignment repo was successfully updated." }
        format.json { render :show, status: :ok, location: @assignment_repo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assignment_repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignment_repos/1 or /assignment_repos/1.json
  def destroy
    @assignment_repo.destroy

    respond_to do |format|
      format.html { redirect_to assignment_repos_path, status: :see_other, notice: "Assignment repo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment_repo
      @assignment_repo = AssignmentRepo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assignment_repo_params
      params.require(:assignment_repo).permit(:student_id, :assignment_id, :repo_url)
    end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: %i[ show edit update destroy ]

  # GET /assignments or /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1 or /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments or /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: "Assignment was successfully created." }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1 or /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: "Assignment was successfully updated." }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1 or /assignments/1.json
  def destroy
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_path, status: :see_other, notice: "Assignment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assignment_params
      params.require(:assignment).permit(:name, :due_date, :description)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_path, status: :see_other, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :slack_link, :github_link, :replit_link, :class_name, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignment_repos_helper.rb
module AssignmentReposHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/assignment_repos/_assignment_repo.html.erb
<div id="<%= dom_id assignment_repo %>">
  <p>
    <strong>Student:</strong>
    <%= assignment_repo.student_id %>
  </p>

  <p>
    <strong>Assignment:</strong>
    <%= assignment_repo.assignment_id %>
  </p>

  <p>
    <strong>Repo url:</strong>
    <%= assignment_repo.repo_url %>
  </p>

</div>

app/views/assignment_repos/_form.html.erb
<%= form_with(model: assignment_repo) do |form| %>
  <% if assignment_repo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(assignment_repo.errors.count, "error") %> prohibited this assignment_repo from being saved:</h2>

      <ul>
        <% assignment_repo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.label :assignment_id, style: "display: block" %>
    <%= form.text_field :assignment_id %>
  </div>

  <div>
    <%= form.label :repo_url, style: "display: block" %>
    <%= form.text_field :repo_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/assignment_repos/edit.html.erb
<h1>Editing assignment repo</h1>

<%= render "form", assignment_repo: @assignment_repo %>

<br>

<div>
  <%= link_to "Show this assignment repo", @assignment_repo %> |
  <%= link_to "Back to assignment repos", assignment_repos_path %>
</div>

app/views/assignment_repos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Assignment repos</h1>

<div id="assignment_repos">
  <% @assignment_repos.each do |assignment_repo| %>
    <%= render assignment_repo %>
    <p>
      <%= link_to "Show this assignment repo", assignment_repo %>
    </p>
  <% end %>
</div>

<%= link_to "New assignment repo", new_assignment_repo_path %>

app/views/assignment_repos/new.html.erb
<h1>New assignment repo</h1>

<%= render "form", assignment_repo: @assignment_repo %>

<br>

<div>
  <%= link_to "Back to assignment repos", assignment_repos_path %>
</div>

app/views/assignment_repos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @assignment_repo %>

<div>
  <%= link_to "Edit this assignment repo", edit_assignment_repo_path(@assignment_repo) %> |
  <%= link_to "Back to assignment repos", assignment_repos_path %>

  <%= button_to "Destroy this assignment repo", @assignment_repo, method: :delete %>
</div>

app/views/assignments/_assignment.html.erb
<div id="<%= dom_id assignment %>">
  <p>
    <strong>Name:</strong>
    <%= assignment.name %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= assignment.due_date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= assignment.description %>
  </p>

</div>

app/views/assignments/_form.html.erb
<%= form_with(model: assignment, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :due_date, class: 'form-label' %>
    <%= form.date_field :due_date, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render "form", assignment: @assignment %>

<br>

<div>
  <%= link_to "Show this assignment", @assignment %> |
  <%= link_to "Back to assignments", assignments_path %>
</div>

app/views/assignments/index.html.erb
<h1>Assignments</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Due Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.name %></td>
        <td><%= assignment.due_date %></td>
        <td>
          <%= link_to 'Show', assignment, class: "btn btn-sm btn-info" %>
          <%= link_to 'Edit', edit_assignment_path(assignment), class: "btn btn-sm btn-warning" %>
          <%= link_to 'Delete', assignment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Assignment', new_assignment_path, class: "btn btn-success" %>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render "form", assignment: @assignment %>

<br>

<div>
  <%= link_to "Back to assignments", assignments_path %>
</div>

app/views/assignments/show.html.erb
<h1><%= @assignment.name %></h1>

<p>
  <strong>Due Date:</strong>
  <%= @assignment.due_date %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment), class: "btn btn-warning" %>
<%= link_to 'Back', assignments_path, class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>

  <!-- Add Name Field -->
  <div class="mb-3">
    <%= form.label :name, "Name", class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <!-- Update Slack DM Field -->
  <div class="mb-3">
    <%= form.label :slack_link, "Slack DM - Channel ID", class: 'form-label' %>
    <%= form.text_field :slack_link, class: 'form-control' %>
  </div>

  <!-- GitHub Field -->
  <div class="mb-3">
    <%= form.label :github_profile, "GitHub Username", class: 'form-label' %>
    <%= form.text_field :github_profile, class: 'form-control' %>
  </div>

  <!-- Replit Field -->
  <div class="mb-3">
    <%= form.label :replit_profile, "Replit Username", class: 'form-label' %>
    <%= form.text_field :replit_profile, class: 'form-control' %>
  </div>

  <!-- Cohort Dropdown -->
  <div class="mb-3">
    <%= form.label :cohort, "Cohort", class: 'form-label' %>
    <%= form.select :cohort, options_for_select(['Cohort 1', 'Cohort 2', 'Cohort 3']), {}, class: 'form-control' %>
  </div>

  <!-- Active Checkbox -->
  <div class="form-check mb-3">
    <%= form.check_box :active, class: 'form-check-input' %>
    <%= form.label :active, "Active", class: 'form-check-label' %>
  </div>

  <!-- Assignments Dropdown -->
  <div class="mb-3">
    <%= form.label :assignment_ids, "Assignments", class: 'form-label' %>
    <%= form.collection_select(:assignment_ids, Assignment.all, :id, :name, { prompt: "Select Assignments" }, { multiple: true, class: 'form-control' }) %>
  </div>

  <!-- Submit Button -->
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Slack link:</strong>
    <%= student.slack_link %>
  </p>

  <p>
    <strong>Github link:</strong>
    <%= student.github_link %>
  </p>

  <p>
    <strong>Replit link:</strong>
    <%= student.replit_link %>
  </p>

  <p>
    <strong>Class name:</strong>
    <%= student.cohort %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= student.active %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<h1>Students</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th> <!-- Add this for student names -->
      <th>Slack</th>
      <th>GitHub</th>
      <th>Replit</th>
      <th>Class Name</th>
      <th>Active</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= link_to "Slack", student.slack_link, target: "_blank" %></td>
        <td><%= link_to "GitHub", student.github_profile, target: "_blank" %></td>
        <td><%= link_to "Replit", student.replit_profile, target: "_blank" %></td>
        <td><%= student.cohort %></td>
        <td><%= student.active? ? "Yes" : "No" %></td>
        <td>
          <%= link_to 'Show', student, class: "btn btn-sm btn-info" %>
          <%= link_to 'Edit', edit_student_path(student), class: "btn btn-sm btn-warning" %>
          <%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Student', new_student_path, class: "btn btn-success" %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>

<p>
  <strong>Slack DM - Channel ID:</strong>
  <%= link_to "DM on Slack", "https://codethedream.slack.com/app_redirect?channel=#{@student.slack_link}", target: "_blank" %>
</p>

<p>
  <strong>Slack DM - Channel ID:</strong>
  <%= link_to "DM on Slack", "https://codethedream.slack.com/app_redirect?channel=#{@student.slack_link}", target: "_blank" %>
</p>

<p>
  <strong>GitHub:</strong>
  <%= link_to "View Repositories", "https://github.com/#{@student.github_profile}?tab=repositories", target: "_blank" %>
</p>

<p>
  <strong>Replit:</strong>
  <%= link_to "View Replit Profile", "https://replit.com/@#{@student.replit_profile}", target: "_blank" %>
</p>

<p>
  <strong>Cohort:</strong>
  <%= @student.cohort %>
</p>

<p>
  <strong>Active:</strong>
  <%= @student.active? ? "Yes" : "No" %>
</p>

<h2>Assignments</h2>
<ul>
  <% @student.assignments.each do |assignment| %>
    <li><%= link_to assignment.name, assignment_path(assignment) %> (Due: <%= assignment.due_date %>)</li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_student_path(@student), class: "btn btn-warning" %>
<%= link_to 'Back', students_path, class: "btn btn-secondary" %>